- name: Add hstore database extension
  become: True
  become_user: "{{ postgresql_admin_user }}"
  shell: "{{ postgresql_bin_path }}/psql {{ item.name }} --username {{ postgresql_admin_user }} - c 'CREATE EXTENSION IF NOT EXISTS hstore'"
  with_items: "{{ postgresql_databases }}"
  register: hstore_ext_result
  failed_when: hstore_ext_result.rc != 0 and ("already exists, skipping" not in hstore_ext_result.stderr)
  changed_when: hstore_ext_result.rc == 0 and ("already exists, skipping" not in hstore_ext_result.stderr)
  when: item.hstore is defined and item.hstore