---
- name: Install PostGIS
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libgeos-c1
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
    - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
  notify:
    - restart postgresql
  tags: postgresql