---
- name: Install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - ca-certificates
    - postgresql
    - postgresql-client
    - postgresql-client-common
    - libpq-dev
    - locales
    - python-psycopg2
    - python-pycurl
  tags: postgresql

- name: Add PostgreSQL repository apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  tags: postgresql

- name: Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  tags: postgresql

- name: Add PostgreSQL repository preferences
  copy:
    src: postgresql.apt.pref
    dest: "{{ postgresql_apt_preferences_path }}"
  tags: postgresql

- name: Install PostgreSQL
  apt:
    name: "{{ item }}"
    state: latest
  environment: "{{ postgresql_env }}"
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-client-{{ postgresql_version }}"
    - "postgresql-contrib-{{ postgresql_version }}"
  tags: postgresql

- name: Install extensions
  include: extensions.yml
  tags: postgresql

- name: Configure
  include: configure.yml
  tags: postgresql
