- name: Update the user privileges
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db | default(omit) }}"
    port: "{{ postgresql_port }}"
    state: present
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  become: True
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_privileges }}"
  when: "{{ postgresql_user_privileges }}|length > 0"